import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function previewCertificate(certificate) {
  const element = createCertificateElement(certificate);

  document.body.appendChild(element);

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
  });

  document.body.removeChild(element);

  const imgData = canvas.toDataURL("image/png");

  const preview = window.open("", "_blank");

  preview.document.write(`
    <html>
      <head>
        <title>Certificate Preview</title>
        <style>
          body{
            margin:0;
            display:flex;
            justify-content:center;
            align-items:center;
            background:#f3f4f6;
            padding:30px;
          }
          img{
            max-width:100%;
            box-shadow:0 10px 25px rgba(0,0,0,.2);
          }
        </style>
      </head>
      <body>
        <img src="${imgData}" />
      </body>
    </html>
  `);

  preview.document.close();
}

export async function downloadCertificate(certificate) {
  const element = createCertificateElement(certificate);

  document.body.appendChild(element);

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
  });

  document.body.removeChild(element);

  const imgData = canvas.toDataURL("image/png");

  const pdf = new jsPDF("landscape", "mm", "a4");

  pdf.addImage(imgData, "PNG", 10, 10, 277, 190);

  pdf.save(`${certificate.course_name}-Certificate.pdf`);
}

function createCertificateElement(certificate) {
  const div = document.createElement("div");

  div.style.width = "1123px";
  div.style.height = "720px";
  div.style.background =
"linear-gradient(135deg,#ffffff,#f8fbff,#eef6ff)";
  div.style.padding = "35px";
  div.style.position = "fixed";
  div.style.left = "-9999px";
  div.style.fontFamily = "Arial, sans-serif";
  div.style.border = "8px solid #2563eb";
div.style.outline = "3px solid #9ec5ff";
div.style.outlineOffset = "-14px";
  div.style.boxSizing = "border-box";
  div.style.textAlign = "center";

div.innerHTML = `
<div style="height:100%;display:flex;flex-direction:column;justify-content:flex-start;">

    <div>
        <div style="font-size:26px;color:#2563eb;font-weight:bold;">
            EDUVERSE AI
        </div>
        <div style="
width:90px;
height:90px;
border-radius:50%;
background:linear-gradient(135deg,#FFD700,#F4B400);
margin:0 auto 20px;
display:flex;
justify-content:center;
align-items:center;
font-size:42px;
box-shadow:0 6px 18px rgba(0,0,0,.2);
">
🏅
</div>

        <h1 style="font-size:48px;color:#1e3a8a;margin:15px 0 5px;">
            Certificate of Achievement
        </h1>

        <div style="width:120px;height:4px;background:#2563eb;margin:auto;border-radius:10px;"></div>

        <p style="font-size:22px;margin-top:35px;color:#555;">
            This certificate is proudly presented to
        </p>

        <h1 style="font-size:46px;color:#111827;margin:15px 0;">
            ${certificate.student_name || "Student"}
        </h1>

        <p style="font-size:22px;color:#555;line-height:1.8;padding:0 80px;">
            For successfully completing the learning program and demonstrating
            excellent performance in assessments conducted through the
            <b>EduVerse AI Learning Platform</b>.
        </p>

        <h2 style="margin-top:30px;font-size:36px;color:#2563eb;">
            ${certificate.course_name}
        </h2>

        <div style="display:flex;justify-content:center;gap:60px;margin-top:35px;font-size:20px;">
            <div>
                <strong>Score</strong><br/>
                ${certificate.score}%
            </div>

            <div>
                <strong>Grade</strong><br/>
                ${certificate.grade}
            </div>

            <div>
                <strong>Subject</strong><br/>
                ${certificate.subject}
            </div>
        </div>
    </div>

    <div style="display:flex;justify-content:space-between;align-items:end;margin-top:20px;">

        <div style="text-align:left;">
            <strong>Issued Date</strong><br/>
            ${new Date(certificate.issued_at).toLocaleDateString()}
        </div>

        <div style="text-align:center;">
            ______________________<br/>
            Authorized Signature
        </div><div style="
margin-top:15px;
text-align:center;
font-size:16px;
color:#666;
border-top:1px solid #ddd;
padding-top:12px;
">
This certificate is digitally generated by <b>EduVerse AI</b> and
verifies successful completion of the learning assessment.
</div>

        <div style="text-align:right;">
            <strong>Certificate ID</strong><br/>
            ${certificate.certificate_id}
        </div>

    </div>

</div>
`;

  return div;
}